### ISSUE TITLE
1.6.0 release checklist

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#3566]
# Post-Beta

* [x] Create stabilization branch
* [x] Create a new transifex resource for branch translation and update the .tx/config section name
* [x] Update the version number of the 'master' branch:
  * [x] In setup.pm, add support to create databases of the version that 'master' becomes
  * [x] In LedgerSMB.pm, increase the $VERSION variable
  * [x] In LedgerSMB::Form, increase the $VERSION variable
  * [x] In sql/Pg-database.sql, increase the `version` setting key in the `defaults` table
  * [x] In bin/ledgersmb-server.psgi, adjust the version-check regex
  * [x] In locale/LedgerSMB.pot, adjust the Project-Id
  * [x] In t/data/Is_LSMB_running.html, the version
  * [x] Update the supported items page: https://ledgersmb.org/faq/which-versions-do-you-support

# General preparation

* [x] Create the .0 release milestone
* [x] Assign the known issues to the release milestone
* [x] Make an announcement on the users, development and announcement lists for translators to become aware of the imminent release
* [x] Notify package maintainers of upcoming release
  * [x] Docker image
  * [x] Debian package
  * [x] (others??)
* [x] Create one or more RC releases
* [x] Fix blocking findings
* [x] Update README.md
* [x] Update the [system requirements listing](https://ledgersmb.org/content/system-requirements)
* [x] Update [list of supported Perl versions](https://ledgersmb.org/faq/which-versions-perl-does-ledgersmb-support)
* [x] Update [list of supported PostgreSQL versions](https://ledgersmb.org/faq/installation/what-versions-postgresql-does-ledgersmb-support)
* [x] Add a taxonomy term to the `Release` taxonomy for the current and upcoming releases
* [x] Create installation documentation on ledgersmb.org
* [x] Create upgrade documentation on ledgersmb.org
* [x] Create [release notes](https://ledgersmb.org/content/16-release-notes) on ledgersmb.org

# Just before release

* [x] Include the new release on the ledgersmb.org front page
* [x] Update the roadmap on ledgersmb.org
* [x] Review installation instructions on ledgersmb.org
  * [x] Including https://ledgersmb.org/content/installing-ledgersmb
* [x] Review README.md
* [x] Update the release date of the minor series in Changelog

# Last step:

* [x] Execute the final release procedure as with a regular (patch) release (but use a different release announcement text)
* [x] Update https://ledgersmb.org/content/download to include the new release (and remove the old!)
      Update: "current stable release line is X.X."  Update download, install, update url, "Docker Images" and 
      "Keeping up with the latest developments" sections.
* [x] Update https://ledgersmb.org/system-requirements to include the new release - check requirements table.
* [x] Update the wikipedia page to include the new release (and remove the old!)

# Post release steps:

* [ ] Update the screenshots
  * [ ] ledgersmb.org
* [x] Update new stable [repo](https://www.openhub.net/p/ledgersmb-stable/enlistments) and [badges](https://www.openhub.net/p/ledgersmb-stable/project_badges) url on OpenHUB

**Comment by ehuelsmann** [comment]
Hoping that someone will pick this up without the open issue...
